### PR TITLE
Add water sensor

### PR DESCRIPTION
**Pull request by Tymec**
Implemented driver to support a z-wave [water sensor](https://www.technisat.com/en_XX/Water-Sensor-1/352-11334-11759/?article=0000/9516) device.

TODO:
  - [x] replace placeholder learning mode icon
  - [x] replace placeholder icon

### CODE REVIEW

**Review by KyleTaylorParkins — CHANGES_REQUESTED** [review]
Hi Tymec,

Thank you for contributing to the app!
Your code seems fine and I assume that you own the device and have tested your code with it?

If you change the icons I'm happy to merge the changes into the app and release it.
You can request a device icon from athom by creating an issue in this repo: https://github.com/athombv/homey-vectors-public.

Update this PR when done and I'll look into it.
Again thanks for contributing!

**Comment by Tymec** [comment]
I've updated the icons as requested.

**Review by KyleTaylorParkins — APPROVED** [review]
Looks fine now.

**Comment by KyleTaylorParkins** [comment]
It's available in version 1.5.7 which is now in test. Let me know if everything works fine.

**Comment by Tymec** [comment]
Seems to work as intended in the test version.

**Pull request merged**
